import type { OfferSeed, OfficialPriceSeed, ProductSeed } from "./types";

// Standard-product separation and item grouping follow the MIT-licensed AI Price Radar design.
export const PRODUCT_CATALOG: ProductSeed[] = [
  [
    "chatgpt-account",
    "ChatGPT",
    "ChatGPT 普号",
    "普通账号",
    "account",
    ["chatgpt free", "chatgpt 普号", "gpt free", "gpt 普号"],
  ],
  [
    "chatgpt-services",
    "ChatGPT",
    "Codex / ChatGPT 周边与自助服务",
    "提链、扫码、自助充值、邀请与镜像",
    "service",
    ["codex 周边", "chatgpt 周边", "chatshare", "光明ai", "镜像月卡"],
  ],
  [
    "chatgpt-plus-trial",
    "ChatGPT",
    "ChatGPT Plus 试用订阅",
    "日抛、成品号、网页号",
    "subscription",
    ["chatgpt plus 成品号", "plus 成品号", "plus 日抛", "plus 试用"],
  ],
  [
    "chatgpt-go",
    "ChatGPT",
    "ChatGPT Go",
    "Go 订阅、充值与成品号",
    "subscription",
    ["chatgpt go", "gpt go"],
  ],
  [
    "chatgpt-team",
    "ChatGPT",
    "ChatGPT Team / Business",
    "团队席位、邀请与 K12",
    "subscription",
    ["chatgpt team", "chatgpt business", "gpt team", "k12"],
  ],
  [
    "chatgpt-plus-renewal",
    "ChatGPT",
    "ChatGPT Plus 正价代充",
    "官方充值、正价续费",
    "subscription",
    ["chatgpt plus 充值", "chatgpt plus 续费", "plus 正价代充"],
  ],
  [
    "chatgpt-pro-5x",
    "ChatGPT",
    "ChatGPT Pro 5x",
    "Pro 5x 订阅与充值",
    "subscription",
    ["chatgpt pro 5x", "pro 5x", "100刀"],
  ],
  [
    "chatgpt-pro-20x",
    "ChatGPT",
    "ChatGPT Pro 20x",
    "Pro 20x 订阅与充值",
    "subscription",
    ["chatgpt pro 20x", "pro 20x", "200刀"],
  ],
  [
    "claude-account",
    "Claude",
    "Claude 普号 / 兑换号",
    "普通账号与兑换号",
    "account",
    ["claude free", "claude 普号", "claude 账号", "claude 兑换号"],
  ],
  ["claude-pro", "Claude", "Claude Pro", "个人会员订阅", "subscription", ["claude pro"]],
  [
    "claude-max-5x",
    "Claude",
    "Claude Max 5x",
    "Max 5x 会员",
    "subscription",
    ["claude max 5x", "max 5x"],
  ],
  [
    "claude-max-20x",
    "Claude",
    "Claude Max 20x",
    "Max 20x 会员",
    "subscription",
    ["claude max 20x", "max 20x", "claude max 充值"],
  ],
  [
    "claude-team-premium",
    "Claude",
    "Claude Team Premium",
    "Team Premium",
    "subscription",
    ["claude team premium", "6.25x"],
  ],
  [
    "claude-team-standard",
    "Claude",
    "Claude Team Standard",
    "Team Standard",
    "subscription",
    ["claude team standard", "1.25x"],
  ],
  [
    "gemini-pro-account",
    "Gemini",
    "Gemini Pro 成品号",
    "Pro 成品号与年卡",
    "account",
    ["gemini pro 成品号", "gemini 教育版", "gemini 年卡", "gemini advanced"],
  ],
  [
    "gemini-pro-renewal",
    "Gemini",
    "Gemini Pro 充值/开通",
    "Pro 充值、续费与开通",
    "subscription",
    ["gemini pro 充值", "gemini pro 续费", "gemini pro 开通"],
  ],
  [
    "gemini-ultra",
    "Gemini",
    "Google AI Ultra / Gemini Ultra",
    "Ultra 会员",
    "subscription",
    ["google ai ultra", "gemini ultra"],
  ],
  [
    "grok-account",
    "Grok",
    "Grok 普号 / 体验号",
    "普通账号与体验号",
    "account",
    ["grok 普号", "grok free", "grok 体验号"],
  ],
  [
    "grok-super",
    "Grok",
    "SuperGrok",
    "SuperGrok 订阅与充值",
    "subscription",
    ["supergrok", "grok super", "super grok"],
  ],
  [
    "grok-heavy",
    "Grok",
    "SuperGrok Heavy / Grok Heavy",
    "Heavy 会员",
    "subscription",
    ["supergrok heavy", "grok heavy"],
  ],
  [
    "outlook-email",
    "邮箱",
    "Outlook / Hotmail 邮箱",
    "Microsoft 邮箱",
    "email",
    ["outlook", "hotmail"],
  ],
  ["other-email", "邮箱", "其他邮箱", "其他邮箱账号", "email", ["其他邮箱", "邮箱账号"]],
  [
    "icloud-email",
    "邮箱",
    "iCloud 邮箱",
    "Apple iCloud 邮箱",
    "email",
    ["icloud 邮箱", "icloud mail"],
  ],
  ["gmail-email", "邮箱", "Gmail / Google 邮箱", "Google 邮箱", "email", ["gmail", "google 邮箱"]],
  ["education-email", "邮箱", "教育邮箱", "Edu 邮箱", "email", ["教育邮箱", "edu 邮箱"]],
  [
    "paypal-verification",
    "接码",
    "PayPal 接码",
    "PayPal 验证服务",
    "verification",
    ["paypal 接码", "paypal 验证"],
  ],
  [
    "openai-verification",
    "接码",
    "OpenAI / ChatGPT 接码",
    "OpenAI 验证服务",
    "verification",
    ["openai 接码", "chatgpt 接码", "实体卡接码"],
  ],
  [
    "google-verification",
    "接码",
    "Google / Gemini 接码",
    "Google 验证服务",
    "verification",
    ["google 接码", "gemini 接码"],
  ],
  [
    "generic-verification",
    "接码",
    "通用接码",
    "短信与手机号验证",
    "verification",
    ["通用接码", "短信验证", "手机号验证"],
  ],
  [
    "identity-service",
    "验证",
    "真人 / KYC 验证",
    "身份验证服务",
    "verification",
    ["kyc", "真人验证"],
  ],
  [
    "cursor-account",
    "编程工具",
    "Cursor 账号",
    "Cursor Pro、激活器与工具",
    "developer-tool",
    ["cursor pro", "cursor 激活器", "cursor 独享号"],
  ],
  [
    "kiro-free",
    "编程工具",
    "Kiro 普号 / Free",
    "Kiro 免费账号",
    "developer-tool",
    ["kiro free", "kiro 普号"],
  ],
  [
    "kiro-pro",
    "编程工具",
    "Kiro Pro / 额度号",
    "Kiro Pro 与额度",
    "developer-tool",
    ["kiro pro", "kiro 额度"],
  ],
  [
    "windsurf-account",
    "编程工具",
    "Windsurf 账号",
    "Windsurf 会员与账号",
    "developer-tool",
    ["windsurf"],
  ],
  [
    "perplexity-account",
    "AI 工具",
    "Perplexity 账号",
    "Perplexity Pro",
    "subscription",
    ["perplexity"],
  ],
  ["suno-account", "AI 工具", "Suno 账号", "Suno 音乐会员", "subscription", ["suno"]],
  [
    "dreamina-account",
    "AI 工具",
    "Dreamina / 即梦",
    "即梦与视频生成",
    "subscription",
    ["dreamina", "即梦"],
  ],
  [
    "apple-id",
    "社媒与账号",
    "Apple ID / 苹果账号",
    "Apple ID",
    "account",
    ["apple id", "苹果账号"],
  ],
  [
    "x-account",
    "社媒与账号",
    "X / 推特账号",
    "X / Twitter 成品账号",
    "account",
    ["推特账号", "twitter 账号", "x 账号"],
  ],
  [
    "x-premium",
    "社媒与账号",
    "X Premium / 推特会员",
    "Premium 与 Premium+",
    "subscription",
    ["x premium", "推特会员", "premium+"],
  ],
  [
    "telegram-account",
    "社媒与账号",
    "Telegram 账号",
    "Telegram 地区号与成品号",
    "account",
    ["telegram 账号", "tg 账号"],
  ],
  [
    "telegram-premium",
    "社媒与账号",
    "Telegram Premium / Pro 会员",
    "Premium 与 Stars",
    "subscription",
    ["telegram premium", "tg premium", "telegram stars"],
  ],
  [
    "virtual-card",
    "支付",
    "虚拟卡",
    "VISA / MasterCard 虚拟卡",
    "payment",
    ["虚拟卡", "visa", "mastercard"],
  ],
  ["gift-card", "支付", "礼品卡", "Apple 与通用礼品卡", "payment", ["礼品卡", "gift card"]],
  [
    "openai-api-credit",
    "API",
    "OpenAI API 额度",
    "API Key 与额度",
    "api",
    ["openai api", "gpt api", "api 额度"],
  ],
  [
    "ai-api-relay",
    "API",
    "AI API 中转",
    "Claude、Gemini、Codex 与多模型中转",
    "api",
    ["中转", "relay", "claude/gemini/codex", "codex 中转", "柴犬"],
  ],
  [
    "minimax-coding-plan",
    "API",
    "MiniMax Coding Plan",
    "MiniMax 编程套餐与中转",
    "api",
    ["minimax", "coding plan"],
  ],
  ["other-product", "其他", "其他商品", "尚未稳定归类的商品", "other", ["其他商品"]],
].map(([slug, platform, name, subtitle, productType, aliases], index) => ({
  slug: slug as string,
  platform: platform as string,
  name: name as string,
  subtitle: subtitle as string,
  productType: productType as string,
  aliases: aliases as string[],
  description: `聚合公开可核验的${name as string}报价、库存、交付与更新时间。`,
  sortOrder: index + 1,
}));

export const AIVORA_OFFERS: OfferSeed[] = [
  [
    "1",
    "chatgpt-go",
    "ChatGPT Go｜充值续费【月卡】",
    "https://www.aivora.cn/products/chong-zhi-xu-fei-yue-ka",
    "https://www.aivora.cn/uploads/goods/3888f4b32aa818d66a0686c0caf9e4ba.webp",
    59,
    undefined,
    "subscription",
  ],
  [
    "46",
    "chatgpt-plus-trial",
    "ChatGPT Plus｜成品号【月卡】",
    "https://www.aivora.cn/products/cheng-pin-hao-yue-ka",
    "https://www.aivora.cn/uploads/goods/optimized/2026/08/price-sync-p46-149-20260825.webp",
    149,
    undefined,
    "account",
  ],
  [
    "2",
    "chatgpt-plus-renewal",
    "ChatGPT Plus｜充值续费【月卡】",
    "https://www.aivora.cn/products/chong-zhi-xu-fei-yue-ka-1",
    "https://www.aivora.cn/uploads/goods/optimized/2026/07/chatgpt-plus-renew-149-main-20260707.webp",
    149,
    undefined,
    "topup",
  ],
  [
    "4",
    "chatgpt-pro-5x",
    "ChatGPT Pro｜续费充值（月卡）【5x / 100刀】",
    "https://www.aivora.cn/products/xu-fei-chong-zhi-yue-ka-dao",
    "https://www.aivora.cn/uploads/goods/a919032cad4b913204aaaab0f04eee3f.webp",
    699,
    undefined,
    "topup",
  ],
  [
    "68",
    "chatgpt-pro-20x",
    "ChatGPT Pro｜续费充值（月卡）【20x / 200刀】",
    "https://www.aivora.cn/products/chatgpt-pro-20x-renewal-monthly",
    "https://www.aivora.cn/uploads/goods/chatgpt-pro-20x-main-1299-20260630.webp",
    1299,
    undefined,
    "topup",
  ],
  [
    "7",
    "openai-verification",
    "ChatGPT Codex｜美国实体卡接码验证（长效）",
    "https://www.aivora.cn/products/mei-guo-shi-ti-ka-jie-ma-yan-zheng-zhang-xiao",
    "https://www.aivora.cn/uploads/goods/optimized/2026/08/price-sync-p7-8-9-20260825.webp",
    8.9,
    undefined,
    "service",
  ],
  [
    "14",
    "chatgpt-services",
    "ChatGPT Plus｜国内镜像月卡（光明AI 新UI）",
    "https://www.aivora.cn/products/guo-nei-jing-xiang-yue-ka-guang-ming-xin",
    "https://www.aivora.cn/uploads/goods/optimized/2026/08/p14-chatgpt-only-22792d703015.webp",
    49,
    undefined,
    "mirror",
  ],
  [
    "28",
    "chatgpt-services",
    "ChatGPT Plus｜国内镜像月卡（ChatShare 经典版）",
    "https://www.aivora.cn/products/guo-nei-jing-xiang-yue-ka-jing-dian-ban",
    "https://www.aivora.cn/uploads/goods/optimized/2026/08/p28-chatgpt-gemini-e8fbfa94c2e1.webp",
    59,
    undefined,
    "mirror",
  ],
  [
    "45",
    "cursor-account",
    "Cursor Pro【独享号】月卡",
    "https://www.aivora.cn/products/du-xiang-hao-yue-ka",
    "https://www.aivora.cn/uploads/goods/cursor-pro-dedicated-95-warranty-30d-20260803.webp",
    95,
    undefined,
    "account",
  ],
  [
    "136",
    "cursor-account",
    "Cursor Pro 激活器",
    "https://www.aivora.cn/products/cursor-pro-activator-packages",
    "https://www.aivora.cn/uploads/goods/optimized/2026/06/p136-180da1bf610e8465b64c806cf59ae3b1-800q82-fb83d854d8.webp",
    3.9,
    109,
    "service",
  ],
  [
    "133",
    "other-product",
    "Cursor Auto｜换号器",
    "https://www.aivora.cn/products/cursor-auto-switcher-packages",
    "https://www.aivora.cn/uploads/goods/optimized/2026/06/p133-f6f5346657f01968f743b828811b5294-800q82-00bba6c44e.webp",
    6.9,
    13.9,
    "service",
  ],
  [
    "137",
    "ai-api-relay",
    "Claude/Gemini/Codex 三合一【中转】",
    "https://www.aivora.cn/products/claude-gemini-codex-relay-credit-packages",
    "https://www.aivora.cn/uploads/goods/0eec656b63db1d598e1b9fdd22ff11cd.webp",
    4.9,
    469,
    "api",
  ],
  [
    "135",
    "ai-api-relay",
    "CodeX 中转",
    "https://www.aivora.cn/products/codex-relay-credit-packages",
    "https://www.aivora.cn/uploads/goods/optimized/2026/07/codex-relay-models-20260716-800q88.webp",
    4.9,
    145,
    "api",
  ],
  [
    "140",
    "ai-api-relay",
    "柴犬 claude/codex 中转",
    "https://www.aivora.cn/products/shiba-cc-assistant-relay-credit-packages",
    "https://www.aivora.cn/uploads/goods/optimized/2026/07/shiba-claude-codex-relay-main-20260715-800q88.webp",
    9.9,
    999,
    "api",
  ],
  [
    "132",
    "minimax-coding-plan",
    "MiniMax M3｜Coding Plan 中转",
    "https://www.aivora.cn/products/minimax-m3-coding-plan-packages",
    "https://www.aivora.cn/uploads/goods/optimized/2026/06/p132-1c19248d48878bdc832af6979473e359-800q82-580e178072.webp",
    10.9,
    29.9,
    "api",
  ],
  [
    "3",
    "gemini-pro-account",
    "Gemini 教育版｜普通号【年卡】",
    "https://www.aivora.cn/products/jiao-yu-ban-pu-tong-ban-nian-ka-zhi-bao-yi-nian",
    "https://www.aivora.cn/uploads/goods/0826ae936c09c2c8dbf4583f2657ad21.webp",
    39.9,
    undefined,
    "account",
  ],
  [
    "139",
    "gemini-pro-renewal",
    "Gemini Pro｜充值续费【年卡】",
    "https://www.aivora.cn/products/gemini-pro-year-renewal",
    "https://www.aivora.cn/uploads/goods/optimized/2026/08/price-sync-p139-49-9-20260825.webp",
    49.9,
    undefined,
    "topup",
  ],
  [
    "6",
    "gemini-pro-account",
    "Gemini Pro｜成品号【年卡】",
    "https://www.aivora.cn/products/nian-ka-zhi-bao-yi-yue",
    "https://www.aivora.cn/uploads/goods/optimized/2026/08/price-sync-p6-59-9-20260825.webp",
    59.9,
    undefined,
    "account",
  ],
  [
    "53",
    "gemini-pro-account",
    "Gemini Pro｜成品号【年卡】含反重力",
    "https://www.aivora.cn/products/nian-ka-han-fan-zhong-li-bian-ji-qi-zhi-bao-yi-yue",
    "https://www.aivora.cn/uploads/goods/optimized/2026/08/price-sync-p53-79-9-20260825.webp",
    79.9,
    undefined,
    "account",
  ],
  [
    "5",
    "claude-account",
    "Claude Free｜普通账号（开会员专用）",
    "https://www.aivora.cn/products/pu-tong-zhang-hao-kai-hui-yuan-zhuan-yong",
    "https://www.aivora.cn/uploads/goods/optimized/2026/08/price-sync-p5-13-9-20260825.webp",
    13.9,
    undefined,
    "account",
  ],
  [
    "11",
    "claude-pro",
    "Claude Pro｜充值续费（月卡）",
    "https://www.aivora.cn/products/chong-zhi-xu-fei-yue-ka-2",
    "https://www.aivora.cn/uploads/goods/optimized/2026/08/price-sync-p11-149-20260825.webp",
    149,
    undefined,
    "topup",
  ],
  [
    "138",
    "claude-max-20x",
    "Claude Max｜充值续费（月卡）",
    "https://www.aivora.cn/products/claude-max-20x-renewal-monthly",
    "https://www.aivora.cn/uploads/goods/optimized/2026/08/claude-max-renewal-850-main-20260825.webp",
    850,
    1299,
    "topup",
  ],
  [
    "49",
    "grok-super",
    "Grok Super 充值续费【月卡】",
    "https://www.aivora.cn/products/chong-zhi-xu-fei-yue-ka-3",
    "https://www.aivora.cn/uploads/goods/optimized/2026/08/price-sync-p49-190-20260825.webp",
    190,
    undefined,
    "topup",
  ],
  [
    "141",
    "grok-super",
    "Grok Super 充值续费【3个月】",
    "https://www.aivora.cn/products/grok-super-renewal-3-months",
    "https://www.aivora.cn/uploads/goods/optimized/2026/08/price-sync-p141-350-20260825.webp",
    350,
    undefined,
    "topup",
  ],
].map(([sourceOfferId, productSlug, name, url, imageUrl, price, highPrice, deliveryType]) => ({
  sourceOfferId: sourceOfferId as string,
  productSlug: productSlug as string,
  name: name as string,
  url: url as string,
  imageUrl: imageUrl as string,
  price: price as number,
  highPrice: highPrice as number | undefined,
  currency: "CNY",
  stockStatus: "in_stock" as const,
  warranty: "store-terms",
  deliveryType: deliveryType as string,
}));

// Price values are versioned from PlanTrack (MIT) and always display lastChecked + official URL.
export const OFFICIAL_PRICES: OfficialPriceSeed[] = [
  {
    slug: "chatgpt-plus-global",
    productSlug: "chatgpt-plus-renewal",
    vendor: "OpenAI",
    planName: "ChatGPT Plus",
    region: "global",
    price: 20,
    currency: "USD",
    billingPeriod: "month",
    quotaText: "Plus + Codex 配额活动",
    officialUrl: "https://chatgpt.com/pricing",
    lastChecked: "2026-05-07",
  },
  {
    slug: "claude-pro-global",
    productSlug: "claude-pro",
    vendor: "Anthropic",
    planName: "Claude Pro",
    region: "global",
    price: 20,
    currency: "USD",
    billingPeriod: "month",
    quotaText: "相对免费版的扩展用量",
    officialUrl: "https://claude.ai/upgrade",
    lastChecked: "2026-05-07",
  },
  {
    slug: "cursor-pro-global",
    productSlug: "cursor-account",
    vendor: "Cursor",
    planName: "Cursor Pro",
    region: "global",
    price: 20,
    currency: "USD",
    billingPeriod: "month",
    quotaText: "Agent 扩展用量",
    officialUrl: "https://cursor.com/pricing",
    lastChecked: "2026-05-07",
  },
  {
    slug: "gemini-pro-global",
    productSlug: "gemini-pro-renewal",
    vendor: "Google",
    planName: "Google AI Pro",
    region: "global",
    price: null,
    currency: "USD",
    billingPeriod: "month",
    quotaText: "以官方页面当日显示为准",
    officialUrl: "https://one.google.com/about/google-ai-plans/",
    lastChecked: "2026-08-29",
  },
  {
    slug: "grok-super-global",
    productSlug: "grok-super",
    vendor: "xAI",
    planName: "SuperGrok",
    region: "global",
    price: null,
    currency: "USD",
    billingPeriod: "month",
    quotaText: "以官方页面当日显示为准",
    officialUrl: "https://grok.com/",
    lastChecked: "2026-08-29",
  },
];

export function normalizeText(value: string): string {
  return value
    .normalize("NFKC")
    .toLowerCase()
    .replace(/[｜|【】()（）[\]_/\\-]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

export function classifyProduct(value: string): ProductSeed | undefined {
  const normalized = normalizeText(value);
  return PRODUCT_CATALOG.map((product) => ({
    product,
    score: [product.name, ...product.aliases].reduce((best, alias) => {
      const normalizedAlias = normalizeText(alias);
      if (normalized.includes(normalizedAlias))
        return Math.max(best, 1_000 + normalizedAlias.length);
      const tokens = normalizedAlias.split(" ").filter((token) => token.length >= 2);
      const containsCompletePhrase =
        tokens.length >= 2 && tokens.every((token) => normalized.includes(token));
      return containsCompletePhrase ? Math.max(best, normalizedAlias.length) : best;
    }, 0),
  }))
    .filter((candidate) => candidate.score > 0)
    .sort((a, b) => b.score - a.score)[0]?.product;
}

export function itemFingerprint(merchantSlug: string, sourceOfferId: string, name: string): string {
  const normalized = normalizeText(name).replace(/\b\d+(?:\.\d+)?\b/g, "#");
  return `${merchantSlug}:${sourceOfferId}:${normalized}`.slice(0, 240);
}

export function calculateMargin(
  cost: number,
  sellPrice: number,
  feeRate = 0,
): {
  profit: number;
  marginRate: number;
} {
  const fee = sellPrice * Math.max(0, feeRate);
  const profit = sellPrice - cost - fee;
  return {
    profit: Number(profit.toFixed(2)),
    marginRate: sellPrice > 0 ? Number(((profit / sellPrice) * 100).toFixed(2)) : 0,
  };
}
