set statement_timeout = 0;
set lock_timeout = 0;
set idle_in_transaction_session_timeout = 0;
set client_encoding = 'UTF8';
set standard_conforming_strings = on;
select pg_catalog.set_config('search_path', '', false);
set check_function_bodies = false;
set client_min_messages = warning;

create schema if not exists public;
comment on schema public is 'standard public schema';

create type public.offer_status as enum (
  'in_stock',
  'out_of_stock',
  'offline',
  'blacklisted'
);

create function public.protect_manual_offer_override() returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if old.is_manual_override = true
     and new.last_crawled_at is distinct from old.last_crawled_at then
    new.status = old.status;
    new.canonical_product_id = old.canonical_product_id;
    new.is_manual_override = true;
  end if;
  return new;
end;
$$;

create table public.crawler_targets (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  site_url text,
  scrape_url text not null unique,
  scraper_type text,
  is_active boolean default true not null,
  remarks text,
  operational_status text default 'unknown'::text not null,
  last_valid_at timestamptz,
  error_streak integer default 0 not null,
  latest_error_msg text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  is_verified boolean default false not null,
  last_attempt_at timestamptz
);

create table public.product_platforms (
  name text not null unique,
  rule_include jsonb default '[]'::jsonb not null,
  rule_exclude jsonb default '[]'::jsonb not null,
  is_active boolean default true not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  id uuid default gen_random_uuid() primary key,
  sort_order integer default 100 not null
);

create table public.product_catalog (
  slug text not null unique,
  name text not null,
  short_desc text default ''::text not null,
  search_keywords text[] default '{}'::text[] not null,
  is_active boolean default true not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  rule_include jsonb default '[]'::jsonb,
  rule_exclude jsonb default '[]'::jsonb,
  id uuid default gen_random_uuid() primary key,
  platform_id uuid not null references public.product_platforms(id) on delete restrict,
  is_catch_all boolean default false,
  sort_order integer default 0 not null,
  seq_id integer generated by default as identity,
  display_id text generated always as (('#'::text || lpad((seq_id)::text, 3, '0'::text))) stored
);

create table public.market_offers (
  id uuid default gen_random_uuid() primary key,
  target_id uuid references public.crawler_targets(id) on delete set null,
  product_title text not null,
  price numeric,
  status public.offer_status default 'in_stock'::public.offer_status not null,
  url text default ''::text not null,
  tags text[] default '{}'::text[] not null,
  inventory_level integer,
  scraped_at timestamptz default now() not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  canonical_product_id uuid references public.product_catalog(id) on delete set null,
  is_manual_override boolean default false,
  last_crawled_at timestamptz,
  constraint unique_target_product unique (target_id, product_title)
);

create table public.scraper_test_jobs (
  id uuid default gen_random_uuid() primary key,
  scrape_url text not null,
  scraper_type text not null,
  status text default 'pending'::text not null,
  result_data jsonb,
  error_message text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

create table public.user_feedbacks (
  id uuid default gen_random_uuid() primary key,
  offer_id uuid references public.market_offers(id) on delete cascade,
  issue_type text not null,
  description text not null,
  status text default 'pending'::text not null,
  created_at timestamptz default now() not null
);

create table public.user_target_submissions (
  id uuid default gen_random_uuid() primary key,
  name text not null,
  site_url text not null,
  status text default 'pending'::text not null,
  created_at timestamptz default now() not null,
  contact text default ''::text,
  remarks text default ''::text
);

create index idx_crawler_targets_last_attempt_at
  on public.crawler_targets (last_attempt_at nulls first);

create trigger trg_protect_manual_offer_override
before update on public.market_offers
for each row execute function public.protect_manual_offer_override();

create policy "Allow admin all on scraper_test_jobs"
  on public.scraper_test_jobs using (true);
create policy "Allow admin all on user_feedbacks"
  on public.user_feedbacks using (true);
create policy "Allow admin all on user_target_submissions"
  on public.user_target_submissions using (true);
create policy "Allow public insert on user_feedbacks"
  on public.user_feedbacks for insert with check (true);
create policy "Allow public insert on user_target_submissions"
  on public.user_target_submissions for insert with check (true);
create policy "Allow public read access on crawler_targets"
  on public.crawler_targets for select using (true);
create policy "Allow public read access on market_offers"
  on public.market_offers for select using (true);
create policy "Allow public read access on product_catalog"
  on public.product_catalog for select using (true);
create policy "Allow public read access on product_platforms"
  on public.product_platforms for select using (true);
create policy "Allow public read on user_target_submissions"
  on public.user_target_submissions for select using (true);

alter table public.crawler_targets enable row level security;
alter table public.market_offers enable row level security;
alter table public.product_catalog enable row level security;
alter table public.product_platforms enable row level security;
alter table public.scraper_test_jobs enable row level security;
alter table public.user_feedbacks enable row level security;
alter table public.user_target_submissions enable row level security;
