--
-- PostgreSQL database dump
--



-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.10 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

CREATE SCHEMA IF NOT EXISTS public;


--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON SCHEMA public IS 'standard public schema';


--
-- Name: offer_status; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.offer_status AS ENUM (
    'in_stock',
    'out_of_stock',
    'offline',
    'blacklisted'
);


--
-- Name: protect_manual_offer_override(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.protect_manual_offer_override() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
  -- If this row was previously manually overridden by the admin
  IF OLD.is_manual_override = true THEN
    -- If the crawler is updating this row (detected by last_crawled_at changing)
    IF NEW.last_crawled_at IS DISTINCT FROM OLD.last_crawled_at THEN
      -- The crawler is allowed to update price, url, inventory_level, updated_at
      -- But we revert the status and canonical_product_id back to what the admin set
      NEW.status = OLD.status;
      NEW.canonical_product_id = OLD.canonical_product_id;
      -- Preserve the manual override flag
      NEW.is_manual_override = true; 
    END IF;
  END IF;
  RETURN NEW;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: crawler_targets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.crawler_targets (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    site_url text,
    scrape_url text NOT NULL,
    scraper_type text,
    is_active boolean DEFAULT true NOT NULL,
    remarks text,
    operational_status text DEFAULT 'unknown'::text NOT NULL,
    last_valid_at timestamp with time zone,
    error_streak integer DEFAULT 0 NOT NULL,
    latest_error_msg text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    is_verified boolean DEFAULT false NOT NULL,
    last_attempt_at timestamp with time zone
);


--
-- Name: market_offers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.market_offers (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    target_id uuid,
    product_title text NOT NULL,
    price numeric,
    status public.offer_status DEFAULT 'in_stock'::public.offer_status NOT NULL,
    url text DEFAULT ''::text NOT NULL,
    tags text[] DEFAULT '{}'::text[] NOT NULL,
    inventory_level integer,
    scraped_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    canonical_product_id uuid,
    is_manual_override boolean DEFAULT false,
    last_crawled_at timestamp with time zone
);


--
-- Name: product_catalog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_catalog (
    slug text NOT NULL,
    name text NOT NULL,
    short_desc text DEFAULT ''::text NOT NULL,
    search_keywords text[] DEFAULT '{}'::text[] NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    rule_include jsonb DEFAULT '[]'::jsonb,
    rule_exclude jsonb DEFAULT '[]'::jsonb,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    platform_id uuid NOT NULL,
    is_catch_all boolean DEFAULT false,
    sort_order integer DEFAULT 0 NOT NULL,
    seq_id integer NOT NULL,
    display_id text GENERATED ALWAYS AS (('#'::text || lpad((seq_id)::text, 3, '0'::text))) STORED
);


--
-- Name: product_catalog_seq_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.product_catalog ALTER COLUMN seq_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.product_catalog_seq_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: product_platforms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.product_platforms (
    name text NOT NULL,
    rule_include jsonb DEFAULT '[]'::jsonb NOT NULL,
    rule_exclude jsonb DEFAULT '[]'::jsonb NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    sort_order integer DEFAULT 100 NOT NULL
);


--
-- Name: scraper_test_jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.scraper_test_jobs (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    scrape_url text NOT NULL,
    scraper_type text NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    result_data jsonb,
    error_message text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: user_feedbacks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_feedbacks (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    offer_id uuid,
    issue_type text NOT NULL,
    description text NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: user_target_submissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_target_submissions (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    site_url text NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    contact text DEFAULT ''::text,
    remarks text DEFAULT ''::text
);


--
-- Name: crawler_targets crawler_targets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.crawler_targets
    ADD CONSTRAINT crawler_targets_pkey PRIMARY KEY (id);


--
-- Name: market_offers market_offers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_offers
    ADD CONSTRAINT market_offers_pkey PRIMARY KEY (id);


--
-- Name: product_catalog product_catalog_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_catalog
    ADD CONSTRAINT product_catalog_pkey PRIMARY KEY (id);


--
-- Name: product_catalog product_catalog_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_catalog
    ADD CONSTRAINT product_catalog_slug_key UNIQUE (slug);


--
-- Name: product_platforms product_platforms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_platforms
    ADD CONSTRAINT product_platforms_pkey PRIMARY KEY (id);


--
-- Name: scraper_test_jobs scraper_test_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.scraper_test_jobs
    ADD CONSTRAINT scraper_test_jobs_pkey PRIMARY KEY (id);


--
-- Name: product_platforms unique_product_platform_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_platforms
    ADD CONSTRAINT unique_product_platform_name UNIQUE (name);


--
-- Name: crawler_targets unique_scrape_url; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.crawler_targets
    ADD CONSTRAINT unique_scrape_url UNIQUE (scrape_url);


--
-- Name: market_offers unique_target_product; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_offers
    ADD CONSTRAINT unique_target_product UNIQUE (target_id, product_title);


--
-- Name: user_feedbacks user_feedbacks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_feedbacks
    ADD CONSTRAINT user_feedbacks_pkey PRIMARY KEY (id);


--
-- Name: user_target_submissions user_target_submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_target_submissions
    ADD CONSTRAINT user_target_submissions_pkey PRIMARY KEY (id);


--
-- Name: idx_crawler_targets_last_attempt_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_crawler_targets_last_attempt_at ON public.crawler_targets USING btree (last_attempt_at NULLS FIRST);


--
-- Name: market_offers trg_protect_manual_offer_override; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_protect_manual_offer_override BEFORE UPDATE ON public.market_offers FOR EACH ROW EXECUTE FUNCTION public.protect_manual_offer_override();


--
-- Name: market_offers market_offers_canonical_product_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_offers
    ADD CONSTRAINT market_offers_canonical_product_id_fkey FOREIGN KEY (canonical_product_id) REFERENCES public.product_catalog(id) ON DELETE SET NULL;


--
-- Name: market_offers market_offers_target_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.market_offers
    ADD CONSTRAINT market_offers_target_id_fkey FOREIGN KEY (target_id) REFERENCES public.crawler_targets(id) ON DELETE SET NULL;


--
-- Name: product_catalog product_catalog_platform_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.product_catalog
    ADD CONSTRAINT product_catalog_platform_id_fkey FOREIGN KEY (platform_id) REFERENCES public.product_platforms(id) ON DELETE RESTRICT;


--
-- Name: user_feedbacks user_feedbacks_offer_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_feedbacks
    ADD CONSTRAINT user_feedbacks_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.market_offers(id) ON DELETE CASCADE;


--
-- Name: scraper_test_jobs Allow admin all on scraper_test_jobs; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow admin all on scraper_test_jobs" ON public.scraper_test_jobs USING (true);


--
-- Name: user_feedbacks Allow admin all on user_feedbacks; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow admin all on user_feedbacks" ON public.user_feedbacks USING (true);


--
-- Name: user_target_submissions Allow admin all on user_target_submissions; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow admin all on user_target_submissions" ON public.user_target_submissions USING (true);


--
-- Name: user_feedbacks Allow public insert on user_feedbacks; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow public insert on user_feedbacks" ON public.user_feedbacks FOR INSERT WITH CHECK (true);


--
-- Name: user_target_submissions Allow public insert on user_target_submissions; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow public insert on user_target_submissions" ON public.user_target_submissions FOR INSERT WITH CHECK (true);


--
-- Name: crawler_targets Allow public read access on crawler_targets; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow public read access on crawler_targets" ON public.crawler_targets FOR SELECT USING (true);


--
-- Name: market_offers Allow public read access on market_offers; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow public read access on market_offers" ON public.market_offers FOR SELECT USING (true);


--
-- Name: product_catalog Allow public read access on product_catalog; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow public read access on product_catalog" ON public.product_catalog FOR SELECT USING (true);


--
-- Name: product_platforms Allow public read access on product_platforms; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow public read access on product_platforms" ON public.product_platforms FOR SELECT USING (true);


--
-- Name: user_target_submissions Allow public read on user_target_submissions; Type: POLICY; Schema: public; Owner: -
--

CREATE POLICY "Allow public read on user_target_submissions" ON public.user_target_submissions FOR SELECT USING (true);


--
-- Name: crawler_targets; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.crawler_targets ENABLE ROW LEVEL SECURITY;

--
-- Name: market_offers; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.market_offers ENABLE ROW LEVEL SECURITY;

--
-- Name: product_catalog; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.product_catalog ENABLE ROW LEVEL SECURITY;

--
-- Name: product_platforms; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.product_platforms ENABLE ROW LEVEL SECURITY;

--
-- Name: scraper_test_jobs; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.scraper_test_jobs ENABLE ROW LEVEL SECURITY;

--
-- Name: user_feedbacks; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.user_feedbacks ENABLE ROW LEVEL SECURITY;

--
-- Name: user_target_submissions; Type: ROW SECURITY; Schema: public; Owner: -
--

ALTER TABLE public.user_target_submissions ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--



